version: 2

jobs:
  python3:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          command: |
            pip install sphinx sphinx_rtd_theme
            pip install .
            cd doc
            make html
      - store_artifacts:
          path: build/html
          destination: doc
      - store_artifacts:
          path: ~/log.txt
      - persist_to_workspace:
          root: build/html
          paths: .
      - attach_workspace:
          at: build/html
      - run: ls -ltrh build/html
    filters:
      branches:
        ignore: gh-pages

workflows:
  version: 2
  build-doc-and-deploy:
    jobs:
      - python3